### ISSUE TITLE
add recOrder to plugin menu of napari

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/recOrder#38] opened 2022-01-12 22:34 UTC
I closed the form with calibration and acquisition controls, and couldn't get back to recOrder. It seems the plugin is not registered to the menu.

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/2934183/149233693-c109bc65-9920-460e-aa2e-8edc6955da8c.png">

Also, the title of the panel for the plugin reads "Form", instead of recOrder.
<img width="320" alt="image" src="https://user-images.githubusercontent.com/2934183/149234016-b3d8f5c8-9955-4039-9488-fe78fe35841c.png">

**Comment by camFoltz** [comment] 2022-01-12 23:11
So this is a tricky problem that I have been working on recently.  Napari's plugin engine is by design incapable of registering plugins or adding plugins to the menu if they are not fully lower-cased.  This goes for the distribution name of the repo as well which is the unfortunate part.  If we want to release `recOrder` with the capitalization of the 'O', which is indeed what I think we should do, I'll open up an issue in napari to understand their reasoning and see if there is flexibility.

**Comment by mattersoflight** [comment] 2022-01-13 00:34
As we discussed, we can have separate recOrder and napari-recorder repos: with compute, data i/o, and CLI in recOrder and the plugin napari-recorder. As long as pycharm allows debugging napari-recorder with "live dependency", we should be fine.

**Comment by camFoltz** [comment] 2022-01-24 19:04
Going to close this issue as it is now duplicate of #41

**Closed by camFoltz** 2022-01-24 19:04 UTC
