### ISSUE TITLE
[DOC] document the Meadowlark device driver versions that work well with different releases and windows versions

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/recOrder#106] opened 2022-05-04 19:20 UTC
**Suggested improvement**
At AQLM, @ieivanov needed to iterate multiple times to setup device driver for Meadowlark controller. We should document the version(s) that have worked, and host the binaries with the [release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository).

**Comment by talonchandler** [comment] 2022-05-04 20:09
Great idea on including the binaries w/ the release. I like it a lot. 

My impression right now is this repo is where the lab has been keeping the source, compilation settings (.vcproj files, etc), and .dlls: 
https://github.com/mehta-lab/MM_meadowlarkLC_opensource

@ieivanov do you know if the files in that repo up to date, or are there newer versions elsewhere?

**Comment by ieivanov** [comment] 2022-05-09 16:48
I do agree that we should document this, I'll work on that.

The code in https://github.com/mehta-lab/MM_meadowlarkLC_opensource is up to date and we don't change it very often. The problem is that the compiled dlls depend on the MMDevice-SharedRuntime library which occasionally changes between different MM versions (https://micro-manager.org/Building_Micro-Manager_Device_Adapters) - that is why we need a different compilation of the device adapter for different MM nightly builds.

**Comment by talonchandler** [comment] 2022-07-29 22:13
Closing. We are now keeping .dll files up to date with releases through github's releases. For example, here is the 0.1.0 release and it's associated .dll: https://github.com/mehta-lab/recOrder/releases/tag/0.1.0

We have also updated the documentation to point the user to these files. Here's the documentation on the wiki (although the wiki will be defunct soon):
https://github.com/mehta-lab/recOrder/wiki/recOrder-Installation-and-MicroManager-Setup-Guide

And here's the `microscope-installation-guide` from the `docs` folder of the `move-docs` branch (to be merged soon)
https://github.com/mehta-lab/recOrder/blob/move-docs/docs/microscope-installation-guide.md

**Closed by talonchandler** 2022-07-29 22:13 UTC
