### ISSUE TITLE
"Load calibration" when MM is live gives an error

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#280] opened 2022-11-17 01:00 UTC
Clicking "Load calibration" when MM is live errors and gives the attached traceback:

[traceback.txt](https://github.com/mehta-lab/recOrder/files/10026782/traceback.txt)

Easy to work around by turning off "Live Mode". 

Related to #203 and #205.

**Comment by ziw-liu** [comment] 2022-11-17 19:24
I was not able to reproduce this error on the Automaton. @talonchandler Can you post more details?

**Comment by talonchandler** [comment] 2022-11-18 17:43
Thanks Ziwen. I just reproduced this error and hummingbird and confirmed that #282 does not fix the issue. 

I'm seeing the error on hummingbird with the `Hummingbird_Stable_Cell_PrimeBSI_LC_LED.cfg` and the loaner PrimeBSI.

Since we've only seen this error on the loaner PrimeBSI and I'm fairly sure this error didn't occur with the PrimeBSI express, I'll take this issue off of 0.3.0 but leave it open to remind ourselves to check.

**Comment by ziw-liu** [comment] 2023-02-09 23:14
@talonchandler @Soorya19Pradeep Have you encountered this issue again? If it's specific to the loaner camera I think we can close this.

**Comment by talonchandler** [comment] 2023-02-14 22:44
I just tested on hummingbird, and this issue is still present. 

I think this issue is low priority. The loading works correctly, and the error message only appears in napari's notifications. Nothing crashes.

**Closed** 2023-04-12 21:38 UTC
Labels: bug
